config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :domitories do
    resources :posts
  end
  # resources :posts
  get 'welcome/door'
  get 'welcome/open' => "welcome#open"
  get 'welcome/dooropen'
  get 'welcome/dooropenfail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/domitory.rb
class Domitory < ApplicationRecord
  has_many :posts, dependent: :destroy
  as_enum :post_type, bulletin: 0, blog: 1, gallery: 2
end

app/controllers/domitories_controller.rb
class DomitoriesController < ApplicationController
  before_action :set_domitory, only: [:show, :edit, :update, :destroy]

  # GET /domitories or /domitories.json
  def index
    @domitories = Domitory.all
  end

  # GET /domitories/1 or /domitories/1.json
  def show
  end

  # GET /domitories/new
  def new
    @domitory = Domitory.new
  end

  # GET /domitories/1/edit
  def edit
  end

  # POST /domitories or /domitories.json
  def create
    @domitory = Domitory.new(domitory_params)

    respond_to do |format|
      if @domitory.save
        format.html { redirect_to @domitory, notice: "Domitory was successfully created." }
        format.json { render :show, status: :created, location: @domitory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @domitory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domitories/1 or /domitories/1.json
  def update
    respond_to do |format|
      if @domitory.update(domitory_params)
        format.html { redirect_to @domitory, notice: "Domitory was successfully updated." }
        format.json { render :show, status: :ok, location: @domitory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @domitory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domitories/1 or /domitories/1.json
  def destroy
    @domitory.destroy
    respond_to do |format|
      format.html { redirect_to domitories_url, notice: "Domitory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domitory
      @domitory = Domitory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def domitory_params
      params.require(:domitory).permit(:title, :description, :post_type_cd)
    end
end

app/helpers/domitories_helper.rb
module DomitoriesHelper
end

app/views/domitories/_form.html.erb
app/views/domitories/_form.html.erb<%= simple_form_for(@domitory) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :description, input_html: { rows: 5 } %>
  <%= f.input :post_type_cd, collection: enum_option_pairs(Domitory, :post_type, true) %>

</div>

<div class="form-actions">
  <%= f.button :submit %>
  <%= link_to 'Show', @domitory, class: 'btn btn-default' if @domitory.persisted? %>
  <%= link_to 'List', domitories_path, class: 'btn btn-default' %>
</div>
<% end %>

app/views/domitories/edit.html.erb
<h1>Editing Domitory</h1>

<%= render 'form', domitory: @domitory %>

<%= link_to 'Show', @domitory %> |
<%= link_to 'Back', domitories_path %>

app/views/domitories/index.html.erb
<h2>domitory</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data actions</th>
    </tr>
  </thead>

  <tbody>
    <% @domitories.each do |domitory| %>
    <tr>
      <td><%= domitory.title %></td>
      <td><%= domitory.description %></td>
      <td>
        <%= link_to 'Show', domitory, class: 'btn btn-default' %>
        <%= link_to 'Edit', edit_domitory_path(domitory), class: 'btn btn-default' %>
        <%= link_to 'Destroy', domitory, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
    </tr>
    </td>

    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Domitory', new_domitory_path, class: 'btn btn-default' %>

app/views/domitories/new.html.erb
<h1>New Domitory</h1>

<%= render 'form', domitory: @domitory %>

<%= link_to 'Back', domitories_path %>

app/views/domitories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @domitory.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @domitory.description %>
</p>

<%= link_to 'Edit', edit_domitory_path(@domitory) %> |
<%= link_to 'Back', domitories_path %>