config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :domitories do
    resources :posts
  end
  # resources :posts
  get 'welcome/door'
  get 'welcome/open' => "welcome#open"
  get 'welcome/dooropen'
  get 'welcome/dooropenfail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  mount_uploader :picture, PictureUploader
  belongs_to :domitory

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_domitory
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
        @posts = @domitory.present? ? @domitory.posts.all : Post.all
  end

  def show
    @posts = Post.new
  end

  def new
    @post = @domitory.present? ? @domitory.posts.new : Post.new
  end

  def edit
  end

  def create
    @post = @domitory.present? ? @domitory.posts.new(post_params) : Post.new(post_params)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to (@domitory.present? ? [@post.domitory, @post] : @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to (@domitory.present? ? [@post.domitory, @post] : @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to (@domitory.present? ? domitory_posts_url(@domitory) : posts_url), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_domitory
    @domitory = Domitory.find(params[:domitory_id]) if params[:domitory_id].present?
  end

  def set_post
    if @domitory.present?
      @post = @domitory.posts.find(params[:id])
    else
      @post = Post.find(params[:id])
    end
  end

  def post_params
  params.require(:post).permit(:title, :content, :picture, :picture_cache)
  end
end 

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container" style="background-color: white;">
  <%= simple_form_for(@domitory.present? ? [@post.domitory, @post] : @post) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :title, placeholder: "이 사람의 이름을 적어주세요!" %>
    <%= f.input :content, placeholder: "이 사람에 대한 설명을 자세히 적어주세요!", input_html: { rows: 10 } %>
    <% if @post.domitory.post_type == :gallery %>
    <%= f.input :picture, as: :file %>
    <%= f.hidden_field :picture_cache %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Show', (@domitory.present? ? [@post.domitory, @post] : @post),style: 'border: 1px solid black;', class: 'btn btn-default' if @post.persisted? %>
    <%= link_to 'List', (@domitory.present? ? domitory_posts_path(@domitory) : posts_path), class: 'btn btn-default' %>
  </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<li>
  <span class='label label-default'><%= post.try(:domitory).try(:title) %></span>
  <%= link_to post.title, [post.domitory, post] %>
  <%= time_ago_in_words(post.created_at) %> ago
</li>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= content_for :header do %>
  <%= render 'shared/header' %>
<% end %>
<%= render "posts/post_types/#{@domitory.post_type}" %>

app/views/posts/new.html.erb
<h1 class="centersentence">New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<table class='table' style="background-color: pink;">
  <div class="characterpicture" , style="margin: 20px;">
    <%= image_tag @post.picture_url, :style => "border-radius: 50px;"%>
  </div>
  <div>
    <div class="titlehead">N A M E</div>
    <div class="titlebody"><%= @post.title %></div>
  </div>
  <br>
  <div>
    <div class="titlehead">D E S C R I P T I O N</div>
    <div class="titlebody"><%= @post.content %></div>
  </div>
  <% if @post.domitory.post_type == :gallery %>
  <% end %>
  <!-- 생성시각
  <tr>
    <th>Created at</th>
    <td><%= @post.created_at %></td>
  </tr>
-->
</table>
<% link_to 'Edit', (@domitory.present? ? edit_domitory_post_path(@domitory)  : edit_post_path(@post)), class: 'btn btn-default' %>
<%= link_to 'List', (@domitory.present? ? domitory_posts_path(@domitory) : posts_path), class: 'ui inverted orange button', style:"position: absolute; right: 0; " %>

<%= render "comments/comments" %>