config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :domitories do
    resources :posts
  end
  # resources :posts
  get 'welcome/door'
  get 'welcome/open' => "welcome#open"
  get 'welcome/dooropen'
  get 'welcome/dooropenfail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  mount_uploader :picture, PictureUploader
  belongs_to :domitory

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_domitory
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
        @posts = @domitory.present? ? @domitory.posts.all : Post.all
  end

  def show
    @posts = Post.new
  end

  def new
    @post = @domitory.present? ? @domitory.posts.new : Post.new
  end

  def edit
  end

  def create
    @post = @domitory.present? ? @domitory.posts.new(post_params) : Post.new(post_params)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to (@domitory.present? ? [@post.domitory, @post] : @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to (@domitory.present? ? [@post.domitory, @post] : @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to (@domitory.present? ? domitory_posts_url(@domitory) : posts_url), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_domitory
    @domitory = Domitory.find(params[:domitory_id]) if params[:domitory_id].present?
  end

  def set_post
    if @domitory.present?
      @post = @domitory.posts.find(params[:id])
    else
      @post = Post.find(params[:id])
    end
  end

  def post_params
  params.require(:post).permit(:title, :content, :picture, :picture_cache)
  end
end 

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/post_types/_gallery.html.erb
<div class="tqtq">
  <div class="container">
    <% @posts.each do | post | %>
    <%= link_to [post.domitory, post] do %>

    <div class="row" , style="margin: 20px;">

      <div class="column">
        <%= image_tag(post.picture_url(:thumb), :style=>" border-radius: 50px; border: 1px solid black; width:") %>
      </div>

      <div class="column">
        <h3>
          N A M E :
        </h3>
        <div class='title' style="padding: 5px; text-align: center; color: black; background-color: white; border-radius:20px; margin-top:3px; border: 1px solid black;"><%= post.title %></div>
        <br />
        <h3>
          D E S C :
        </h3>
        <div class='content over' style="padding: 5px; text-align: center; color: black; background-color: rgb(254, 200, 107); border-radius:20px; margin-top:3px; border: 1px solid black;"><%= post.content %></div>
      </div>

    </div>
    <div class="ui section divider"></div>
    <% end if post.picture?%>
    <!--
      <div class='actions'>
        <%= link_to [post.domitory, post] do %>
        <i class="fa fa-eye"></i>
        <% end %>
        -->

    <!--
        <%= link_to edit_domitory_post_path(post.domitory, post) do %>
        <i class="fa fa-edit"></i>
        <% end %>
        -->

    <!--
        <%= link_to fa_icon('trash'), [post.domitory, post], method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
        -->
    <% end %>
  </div>
  <div class="makepicture">
    <%= link_to 'Add Character', new_domitory_post_path, class: 'ui red button' %>
  </div>
</div>
<%= render 'shared/container' %>